<?php

/*
 * Words and phrases blocked by App\Support\ProfanityFilter. Matched as whole
 * words (case-insensitive). Edit this list to reflect your moderation policy.
 *
 * Keep entries lowercase. Multi-word phrases work too. For project-specific
 * additions you'd rather not commit to source control, set the env var
 * PROFANITY_EXTRA_WORDS to a comma-separated list — those are merged with the
 * defaults at runtime.
 *
 * NOTE: This list covers strong English profanity, common variations, racial
 * and identity-based slurs, and basic evasion patterns. Review periodically
 * and extend for non-English content or additional moderation needs.
 */

return [
    'words' => array_values(array_filter(array_unique(array_merge(
        [
            // Strong profanity and common variations
            'fuck',
            'fucker',
            'fuckers',
            'fucking',
            'fucked',
            'fucks',
            'fuckface',
            'fuckwit',
            'fuckboy',
            'shit',
            'shitty',
            'shithead',
            'shitface',
            'shithole',
            'shitstain',
            'bullshit',
            'horseshit',
            'batshit',
            'asshole',
            'assholes',
            'arse',
            'arsehole',
            'bitch',
            'bitches',
            'bitchy',
            'bastard',
            'bastards',
            'dickhead',
            'motherfucker',
            'motherfuckers',
            'motherfucking',
            'cunt',
            'cunts',

            // Sexual and anatomical terms used as insults
            'cock',
            'cocksucker',
            'cocksuckers',
            'dick',
            'dicks',
            'pussy',
            'twat',
            'wanker',
            'wankers',
            'whore',
            'whores',
            'slut',
            'sluts',
            'skank',
            'skanky',
            'blowjob',
            'handjob',
            'jackoff',
            'jerkoff',
            'dildo',
            'dildos',
            'cumshot',
            'jizz',
            'boobs',
            'titties',
            'ballsack',
            'nutsack',

            // Racial and ethnic slurs
            'nigger',
            'niggers',
            'nigga',
            'niggas',
            'chink',
            'chinks',
            'gook',
            'gooks',
            'kike',
            'kikes',
            'spic',
            'spics',
            'wetback',
            'wetbacks',
            'beaner',
            'beaners',
            'wop',
            'wops',
            'dago',
            'dagos',
            'raghead',
            'ragheads',
            'towelhead',
            'towelheads',
            'camel jockey',
            'sand nigger',
            'paki',
            'pakis',
            'coon',
            'coons',
            'darkie',
            'darkies',
            'redskin',
            'redskins',
            'injun',
            'squaw',
            'honky',
            'gringo',
            'gringos',
            'jap',
            'japs',
            'zipperhead',

            // Homophobic and transphobic slurs
            'fag',
            'fags',
            'faggot',
            'faggots',
            'dyke',
            'dykes',
            'tranny',
            'trannies',
            'shemale',
            'shemales',
            'homo',
            'homos',
            'lesbo',
            'lesbos',

            // Disability-related slurs
            'retard',
            'retards',
            'retarded',
            'spaz',
            'spazz',
            'spastic',
            'cripple',
            'cripples',
            'mongoloid',

            // Religious slurs
            'christkiller',

            // General strong insults and compound terms
            'douchebag',
            'douchebags',
            'douche',
            'dumbass',
            'jackass',
            'smartass',
            'fatass',
            'lardass',
            'dumbfuck',
            'clusterfuck',
            'ratfuck',
            'dipshit',
            'numbnuts',
            'peckerhead',
            'prick',
            'pricks',
            'scumbag',
            'scumbags',
            'sleazebag',
            'scrotum',
            'turd',
            'turds',

            // Common evasions (leet-speak / substitution)
            'f u c k',
            'f-u-c-k',
            's h i t',
            's-h-i-t',
            'b i t c h',
            'b-i-t-c-h',
            'n i g g e r',
            'n-i-g-g-e-r',
            'phuck',
            'phuk',
            'fuk',
            'fuq',
            'fck',
            'sh1t',
            'b1tch',
            'azz',
            'azzhole',
        ],
        array_map('trim', array_filter(explode(',', (string) env('PROFANITY_EXTRA_WORDS', '')))),
    )))),
];
