<?php

namespace App\Jobs;

use App\Enums\TemplateGeneratorStyle;
use App\Models\User;
use App\Services\ProceduralTemplateGenerator;
use App\Services\TemplateDraftSaver;
use App\Support\TemplateSearchOptions;
use Filament\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Queue\Queueable;
use Throwable;

/**
 * Generates procedural templates in the background and tells the admin who
 * asked for them when the drafts are ready. Used for grids too large to
 * build inside a web request.
 */
class GenerateTemplateDrafts implements ShouldQueue
{
    use Queueable;

    /** Grids above this size are generated by this job rather than in the request. */
    public const int QUEUE_ABOVE_SIZE = 21;

    public int $timeout = 3600;

    public int $tries = 1;

    /**
     * @param  list<int>  $themeLengths
     * @param  array<string, mixed>  $targetOverrides
     * @param  list<array{word: string, direction?: string}>  $seedWords
     */
    public function __construct(
        public int $requestedById,
        public int $size,
        public TemplateGeneratorStyle $style,
        public int $count,
        public ?int $seed,
        public array $themeLengths,
        public array $targetOverrides,
        public TemplateSearchOptions $search,
        public array $seedWords,
    ) {}

    public function handle(ProceduralTemplateGenerator $generator, TemplateDraftSaver $drafts): void
    {
        $candidates = $generator->generate(
            size: $this->size,
            style: $this->style,
            count: $this->count,
            seed: $this->seed,
            themeLengths: $this->themeLengths,
            targetOverrides: $this->targetOverrides,
            search: $this->search,
            seedWords: $this->seedWords,
        );

        $savedIds = $drafts->save($candidates);

        $notification = $savedIds === []
            ? Notification::make()
                ->title("No {$this->size}×{$this->size} templates generated")
                ->body('No valid new grid was found. Try a different seed or loosen the settings.')
                ->warning()
            : Notification::make()
                ->title("{$this->size}×{$this->size} templates ready")
                ->body(sprintf('Saved %d template(s) as inactive drafts.', count($savedIds)))
                ->success();

        $this->notify($notification);
    }

    public function failed(?Throwable $exception): void
    {
        $this->notify(
            Notification::make()
                ->title("{$this->size}×{$this->size} template generation failed")
                ->body($exception?->getMessage() ?? 'The job stopped before finishing.')
                ->danger(),
        );
    }

    private function notify(Notification $notification): void
    {
        $user = User::find($this->requestedById);

        if ($user !== null) {
            $notification->sendToDatabase($user);
        }
    }
}
